# Generated by Django 5.2.17 on 2026-08-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='no_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
